version: '3.9'

services:
  mongo-database:
    build: ./.mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: users
  
  users-api-backend:
    build:
      dockerfile: UsersApi/Dockerfile
    ports:
      - "5001:8080"
    expose:
      - "5001"
    depends_on:
      - mongo-database