version: '3.9'

services:
  mongodb:
    container_name: mongodb
    build:
      dockerfile: mongo/Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/

  users-api-backend:
    container_name: users-api-backend
    build:
      dockerfile: UsersApi/Dockerfile
    ports:
      - "5001:8080"
    expose:
      - "5001"
    depends_on:
      - mongodb